### PR TITLE
Add version checking

### PR DESCRIPTION
**Pull request by faveoled**

### CODE REVIEW

**Comment by JordanL2** [comment]
What exactly is the purpose of this, I've read the docs for [Anitya](https://anitya.readthedocs.io/en/stable/) and it seems to be something about tracking releases, so stuff can be notified when a new release is published?

**Comment by faveoled** [comment]
Yes, also automated pull requests as far as I know (current app version is outdated)

**Comment by JordanL2** [comment]
So it'll automatically make a new PR anytime a new version of CudaText is published? What about all the other dependencies, will it automatically update them at the same time?

**Comment by faveoled** [comment]
You could make it do it if you add additional x-checker-data entries

**Comment by JordanL2** [comment]
Will it make a separate PR for each dependency, anytime a new version of the dependency is created? Or will it wait until a new version of CudaText is released, then make a new PR, which also includes all the new versions of the dependencies? That second one is what we need it to do - I've already got a script that updates all the deps and makes a new PR, I just didn't run it last weekend because I was busy, but I'll do a new release this weekend for sure.

**Comment by faveoled** [comment]
That I don't know

**Comment by JordanL2** [comment]
I can merge it if the release notification stuff is useful to someone, I'm just a little concerned about getting flooded with PRs I can't use from it, is it possible to disable the PRs if we can't use them?

**Comment by faveoled** [comment]
Don't merge if it's not useful to you. You can close the PR

**Pull request closed without merging**
